docs(cn): translate <guide/zh/04-tutorial.md>
docschina/rollupjs.org pull request #11
Opened 2020-07-05 05:51 UTC by Catherine001li

docs(cn): translate <guide/zh/04-tutorial.md>

2020-07-05 16:21 UTC, lcxfs1991 requested changes

2020-07-05 16:21 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +*开始之前,需要安装 [Node.js](https://nodejs.org)， 这样才可以使用 [NPM](https://npmjs.com)；还需要了解如何使用 [command line](https://www.codecademy.com/learn/learn-the-command-line)。*
如何在你的机器上使用[命令行]

2020-07-05 16:21 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +`-f` 可选项 (为 `--format`缩写) 明确我们正创建的是哪类 bundle — 在本项目中，CommonJS (将在 Node.js中运行)。由于我们没有指定一个输出文件，因此将打印到 `stdout` 中:
straight -> 直接

2020-07-05 16:21 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +(也可以使用 `rollup src/main.js -f cjs > bundle.js`, 但是稍后将会明白，如果你使用生成映射的灵活度较低。)
如果你生成 sourcemaps，这种办法灵活度较低

2020-07-05 16:21 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +你可以在配置文件的相同可选项行重写任意可选项:
你可以用命令行中同等的可选项重写配置文件中可选项：

2020-07-05 16:21 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +_注: Rollup 本身执行了配置文件, 因此我们能够使用 `export default` 语法 – 这些代码不能被 Babel 或者其他类似工具转换编译，因此你必须使用你正在使用的 Node.js 版本支持的 ES2015 特性语法。_
这些代码没有被 Babel 或其它工具编译，因此你只能使用Node.js 版本支持的 ES2015 语法特性

2020-07-05 16:21 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +根据你的喜好，也可以由默认的 `rollup.config.js` 派生其他的配置文件：
指定除 `rollup.config.js` 外的其它配置文件：

2020-07-05 16:21 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +一旦安装完成，在 `package.json` 中会增加一个打包脚本，提供给开发者一个简洁的命令。例如：
提供给所有贡献者一个便捷的命令。例如：

2020-07-05 16:21 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +到目前为止，我们已经创建了一个简单的 bundle，从一个入口文件到导入一个相对路径的模块。当创建更复杂的 bundles 时，需要更多的灵活性 - 使用 NPM　安装导入模块，使用　Babel 编译代码，运行 JSON 文件等。
到目前为止，我们已经基于一个入口文件和通过相对路径导入的模块创建了一个简单的 bundle。当你构建更复杂的 bundles 时，

2020-07-05 16:21 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +为此, 使用 *插件*, 将改变 Rollup 在绑定进程中的重要点的行为. 在 [the Rollup Awesome List](https://github.com/rollup/awesome) 中维护着一些优秀的插件。
绑定进程 -> 打包过程

2020-07-05 16:21 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +一些插件专门应用于输出中。查阅 [plugin hooks](guide/en/#build-hooks) 了解关于输出-特定插件能做的更多技术细节。这些插件作用范围较小，仅能在已经编译的 Rollup 主分析之后能更改代码。当输出-特定插件中使用了一个不兼容的插件时，Rollup 会给出警告。出现的可能场景为，在压缩要在浏览器中使用的 bundle 包。
这段有三个点要修改：

1. In a nut-shell -> 总的来说，这些插件仅仅只可以在 Rollup 的主要代码分析完成后，才可以修改代码。

2. 如果一个不适用的插件被当然输出特定插件使用的时候，Rollup 会给出告警。

3. 一个可能出现的使用场景是，浏览器中会使用压缩后的 bundles。

2020-07-05 16:22 UTC, lcxfs1991 commented
Review了一半，问题比较多，建议认真读一下翻译内容，以及结合前端专业知识再进译一遍哈。如果有不理解的地方，可以群里提问

2020-07-06 13:34 UTC, Catherine001li commented
好的，进行修改，非常感谢

2020-07-09 15:25 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +修改你的 `rollup.config.js` 文件，增加第二项压缩输出。 压缩格式, 选择 `iife`。这种格式下包裹代码在浏览器中能够通过 `script` 标签自执行，避免其他代码的植入。当我们导出时，需要提供一个将通过 bundle 创建的全局变量名称，使导出的代码能被其他代码所使用。
修改你的 `rollup.config.js` 文件，增加第二项压缩输出。 压缩格式选择 `iife`。这种格式下包裹代码在浏览器中能够通过 `script` 标签自执行，避免其它代码产生交互。当我们导出时，需要提供由生成 bundle 创建的一个全局变量，这样其它的代码可以通过该变量使用到此导出的代码。

2020-07-09 16:20 UTC, lcxfs1991 requested changes

2020-07-09 16:20 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +除了 `bundle.js` 之外，现在来创建 Rollup 的第二个文件 `bundle.min.js`:
除了 `bundle.js` 之外，Rollup 会创建第二个文件 `bundle.min.js`:

2020-07-09 16:20 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +修改你的 `rollup.config.js` 文件，增加第二项压缩输出。 压缩格式, 选择 `iife`。这种格式下包裹代码在浏览器中能够通过 `script` 标签自执行，避免其他代码的植入。当我们导出时，需要提供一个将通过 bundle 创建的全局变量名称，使导出的代码能被其他代码所使用。
修改你的 `rollup.config.js` 文件，增加第二项压缩输出。 压缩格式选择 `iife`。这种格式下包裹代码在浏览器中能够通过 `script` 标签自执行，避免其它代码产生交互。当我们导出时，需要提供由生成 `bundle` 创建的一个全局变量，这样其它的代码可以通过该变量使用到此导出的代码。

2020-07-09 16:20 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +就代码分割来说, Rollup 有很多场景使用了代码分割自动成块，例如动态加载或者多入口, [`output.manualChunks`](guide/en/#outputmanualchunks) 配置项告诉了 Rollup 哪些模块需要分割成块。
就代码分割来说, Rollup 有很多场景自动将代码切割成块，例如动态加载或者多入口，有一个办法，通过[`output.manualChunks`](guide/en/#outputmanualchunks) 配置项可以显式地告诉了 Rollup 哪些模块需要分割成块。

2020-07-09 16:20 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +为了使用代码分割特性来完成动态懒加载 (仅在一个函数执行之后加载其导入的模块), 回到最初的例子并修改 `src/main.js`，替换静态加载为 动态加载 `src/foo.js`:
为了使用代码分割特性来完成动态懒加载 (仅在一个函数执行之后加载其导入的模块)，我们回到最初的例子并修改 `src/main.js`，将加载 `src/foo.js` 由静态加载改为动态加载:

2020-07-09 16:20 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +Rollup 将采用动态导入的方式去构建一个仅需加载的分片块。为了能让 Rollup 知道哪里是第二个分块，替换 `--file` 可选项，我们使用 `--dir` 可选项设置一个文件夹用来输出:
Rollup 将采用动态导入的方式去构建一个仅需加载的块(chunk)。为了能让 Rollup 知道将分片块放在哪里，我们会使用 `--dir` 选项来替换 `--file` 选项，来设置一个文件夹用来输出:

2020-07-09 16:20 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +在相同输出之前你仍然可以运行你的代码。 `./foo.js` 的加载和编译尽管有一点慢，但是它只会在我们首次调取导出函数时执行一次。
你仍然可以以相同的输出内容运行你的代码，即使加载和解析 `./foo.js`有一点慢，但是它只会在我们首次调用导出函数时执行一次。

2020-07-09 16:20 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +如果我们没有使用 `--dir` 可选项，Rollup 将会再次打印块到 `stdout` 中，添加注释来凸显这个块的边界:
如果我们没有使用 `--dir` 可选项，Rollup 会再次将块信息打印到 `stdout` 中，添加注释来突出这个块的边界:

2020-07-09 16:20 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +注意多个入口如何导入相同的共享块。Rollup 不会复制代码而是会插入额外的满足需求最小新增块。再次，通过 `--dir` 可选项写文件到桌面上。
注意多个入口如何导入相同的共享块。Rollup 不会重复代码而是会新增额外的满足需求最低限度必要的块(chunk)。再次，通过 `--dir` 可选项可将文件写到电脑的硬盘上。

2020-07-09 16:20 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +你可以由不同浏览器规范：本地 ES 模块，AMD 加载或者 SystemJS 打包出相同的代码。
你可以通过原生 ES 模块，符合 AMD 规范的加载器或 SystemJS 为浏览器构建相同的代码。

2020-07-09 16:20 UTC, lcxfs1991 commented on guide/zh/04-tutorial.md
> +参见 [rollup-starter-code-splitting](https://github.com/rollup/rollup-starter-code-splitting) 示例，在有需要的情况下，如何设置一个在浏览器上使用本地 ES 模块的 Web app 回滚到 SystemJs。
参见 [rollup-starter-code-splitting](https://github.com/rollup/rollup-starter-code-splitting) 示例，在有需要的情况下，如何设置一个在浏览器上使用原生 ES 模块的网页应用同时具备回退到 SystemJS 的能力。

2020-07-09 16:21 UTC, lcxfs1991 commented
@Catherine001li  请按上面的review进行更正，感谢！

2020-07-09 23:30 UTC, Catherine001li commented
已进行修改，请查阅，谢谢

2020-07-12 06:58 UTC, merged