docs(cn): translate guide/zh/00-introduction.md
docschina/rollupjs.org pull request #5
Opened 2020-06-28 11:38 UTC by beetaa

introduction 的翻译，请各位帮忙把关斧正，谢谢。 @QC-L

2020-07-02 13:39 UTC, QC-L commented on guide/zh/00-introduction.md
> +[rollup-starter-app](https://github.com/rollup/rollup-starter-app) 两个项目可分别作为 Rollup 运用于库和应用的参考。
```suggestion
[rollup-starter-app](https://github.com/rollup/rollup-starter-app) 两个项目可分别作为 Rollup 
运用于库和应用的参考。
```

2020-07-02 13:40 UTC, QC-L commented on guide/zh/00-introduction.md
> +运用于库和应用的参考。
```suggestion
```

2020-07-02 13:42 UTC, QC-L commented on guide/zh/00-introduction.md
> + Rollup 可以通过两种方式使用：（1）[命令行](guide/en/#command-line-reference)方式，可以为命令行传入一个可选的配置文件；（2）[JavaScript API](guide/en/#javascript-api) 方式。运行 `rollup --help` 可以查看可用的选项和参数。
```suggestion
 Rollup 可以通过两种方式使用：使用[命令行](guide/en/#command-line-reference)方式，可以为命令行传入一个可选的配置文件。或者使用 [JavaScript API](guide/en/#javascript-api) 方式。运行 `rollup --help` 可以查看可用的选项和参数。
```

2020-07-02 13:43 UTC, QC-L commented on guide/zh/00-introduction.md
> +ES6 版本的 Javascript 最终为带来了引入和导出的语法（ES6 Module，译者注），该语法可以让我们在多个脚本中共享函数和数据。虽然这一语法标准已确定下来，但目前仅在较新的浏览器中可以使用，并且 Node.js 也尚未完成该标准的导入。有了 Rollup， 你现在就可以放心地使用新的模块标准来书写代码，并将其编译为当前被广泛支持的 CommonJS、AMD 以及 IIFE 风格等
```suggestion
ES6 版本的 Javascript 最终带来了 import 和 export 的语法（ES6 Module，译者注），该语法可以让我们在多个脚本中共享函数和数据。虽然这一语法标准已确定下来，但目前仅在较新的浏览器中可以使用，并且 Node.js 也尚未完成该标准的导入。有了 Rollup，你现在就可以放心地使用新的模块标准来书写代码，并将其编译为当前被广泛支持的 CommonJS、AMD 以及 IIFE 风格等多种格式。也就是说，你可以用*符合未来标准的代码*来赢得当下广大用户的芳心和敬意。:)
```

2020-07-02 13:44 UTC, QC-L commented on guide/zh/00-introduction.md
> +### 兼容性
```suggestion

### 兼容性
```

2020-07-02 13:45 UTC, QC-L commented on guide/zh/00-introduction.md
> +为了确保你的 ES 模块能够尽快在 Node.js 和 webpack 等支持 CommonJS 格式的工具中可用，你可以使用 Rollup 将代码编译为 UMD 或 CommonJS 格式，然后在 `package.json` 文件的 `main` 属性中指向当前编译的版本。如果你的 `package.json` 文件具有 `module` 属性，像 Rollup 和 [webpack 2+]
```suggestion
为了确保你的 ES 模块能够尽快在 Node.js 和 webpack 等支持 CommonJS 格式的工具中可用，你可以使用 Rollup 将代码编译为 UMD 或 CommonJS 格式，然后在 `package.json` 文件的 `main` 属性中指向当前编译的版本。如果你的 `package.json` 文件具有 `module` 属性，像 Rollup 和 [webpack 2+](https://webpack.js.org/) 这类 ES-module-aware 的工具就可以直接[导入模块的 ES module 版本](https://github.com/rollup/rollup/wiki/pkg.module)。
```

2020-07-02 13:48 UTC, QC-L commented
感谢你的支持，翻译的很棒，点个赞。
但是我们也不是全职搞这个的，我们也是个兴趣小组，大家都是业余时间搞搞的。
所以有时顾不过来的，如果有怠慢还请见谅。

2020-07-03 01:01 UTC, beetaa commented
> 感谢你的支持，翻译的很棒，点个赞。
> 但是我们也不是全职搞这个的，我们也是个兴趣小组，发起这个也纯属爱好，大家都是业余时间搞搞的。
> 所以有时顾不过来的，如果有怠慢还请见谅。

谢谢，校对工作很细致，辛苦了。

2020-07-04 03:16 UTC, lcxfs1991 requested changes

2020-07-04 03:16 UTC, lcxfs1991 commented on guide/zh/00-introduction.md
> +Rollup 是一个 JavaScript 模块打包工具，可以将多个小的代码片段编译为完整的库和应用。与传统的 CommonJS 和 AMD 这一类非标准化的解决方案不同，Rollup 使用的是 ES6 版本 Javascript 中的模块标准。新的 ES 模块可以让你自由、无缝地按需使用你最喜爱的库中那些有用的单个函数。这一特性在未来将随处可用，但 Rollup 让你现在就可以，想用就用。
中英文行数要保持一致哈

2020-07-04 03:16 UTC, lcxfs1991 commented on guide/zh/00-introduction.md
> +为了确保你的 ES 模块能够尽快在 Node.js 和 webpack 等支持 CommonJS 格式的工具中可用，你可以使用 Rollup 将代码编译为 UMD 或 CommonJS 格式，然后在 `package.json` 文件的 `main` 属性中指向当前编译的版本。如果你的 `package.json` 文件具有 `module` 属性，像 Rollup 和 [webpack 2+]
ES-module-aware tools ->  ES 模块识别工具

2020-07-04 03:17 UTC, lcxfs1991 commented
译得不错，还有两个小点，以及每段中英文行数需要对齐哈 @beetaa  beetaa

2020-07-05 07:57 UTC, QC-L commented on guide/zh/00-introduction.md
> +为了确保你的 ES 模块能够尽快在 Node.js 和 webpack 等支持 CommonJS 格式的工具中可用，你可以使用 Rollup 将代码编译为 UMD 或 CommonJS 格式，然后在 `package.json` 文件的 `main` 属性中指向当前编译的版本。如果你的 `package.json` 文件具有 `module` 属性，像 Rollup 和 [webpack 2+]
```suggestion
为了确保你的 ES 模块能够尽快在 Node.js 和 webpack 等支持 CommonJS 格式的工具中可用，你可以使用 Rollup 将代码编译为 UMD 或 CommonJS 格式，然后在 `package.json` 文件的 `main` 属性中指向当前编译的版本。如果你的 `package.json` 文件具有 `module` 属性，像 Rollup 和 [webpack 2+](https://webpack.js.org/) 这类 ES 模块识别工具可以直接[导入模块的 ES module 版本](https://github.com/rollup/rollup/wiki/pkg.module)。
```

2020-07-05 07:57 UTC, QC-L approved these changes

2020-07-05 07:57 UTC, merged