docs(cn): translate guide/zh/07-tools.md
docschina/rollupjs.org pull request #6
Opened 2020-06-29 09:04 UTC by wangxiaocuo

Integrating Rollup With Other Tools 翻译。还请斧正。麻烦啦 @QC-L

2020-07-05 12:12 UTC, lcxfs1991 requested changes

2020-07-05 12:12 UTC, lcxfs1991 commented on guide/zh/07-tools.md
> +有时候，您的项目可能需要依赖于一些 NPM 包。与 Webpack 和 Browserify 等其他打包器不同，Rollup 并不能“开箱即用”地处理 NPM 包的依赖关系——我们需要添加一些配置。
Webpack -> webpack

2020-07-05 12:12 UTC, lcxfs1991 commented on guide/zh/07-tools.md
> +现在运行 Rollup 将创建一个 bundle ——除非我们并未添加任何 ES2015 的功能。 让我们通过编辑 `src/main.js` 来改变它：
除非 -> 除了

2020-07-08 12:09 UTC, wangxiaocuo commented on guide/zh/07-tools.md
> +有时候，您的项目可能需要依赖于一些 NPM 包。与 Webpack 和 Browserify 等其他打包器不同，Rollup 并不能“开箱即用”地处理 NPM 包的依赖关系——我们需要添加一些配置。
已修改。但是原文就是 W 大写，并且 Browserify 也是首字母大写。改成 webpack，会不会有点别扭

2020-07-08 12:14 UTC, wangxiaocuo commented on guide/zh/07-tools.md
> +现在运行 Rollup 将创建一个 bundle ——除非我们并未添加任何 ES2015 的功能。 让我们通过编辑 `src/main.js` 来改变它：
已修改。但是原文的意思大概是如果没有写任何ES2015的代码，babel就不会执行，也并不会创建bundle。改成除了，感觉不太通顺唉...

2020-07-09 14:43 UTC, lcxfs1991 commented on guide/zh/07-tools.md
> +有时候，您的项目可能需要依赖于一些 NPM 包。与 Webpack 和 Browserify 等其他打包器不同，Rollup 并不能“开箱即用”地处理 NPM 包的依赖关系——我们需要添加一些配置。
不会，webpack官方规定，webpack开头就是小写

2020-07-09 14:44 UTC, merged