docs(cn): translate guide/zh/06-faqs.md
docschina/rollupjs.org pull request #9
Opened 2020-06-29 15:42 UTC by parrotdance

翻译常见问题章节

2020-07-04 01:29 UTC, parrotdance commented
@QC-L 翻译已基本完成，劳烦抽空review 🍻

2020-07-04 02:51 UTC, lcxfs1991 requested changes

2020-07-04 02:51 UTC, lcxfs1991 commented on guide/zh/06-faqs.md
> +#### 什么是“Tree-shaking”？
请用小写

2020-07-04 02:51 UTC, lcxfs1991 commented on guide/zh/06-faqs.md
> +ES 模块是一个官方标准，也是 JavaScript 语言明确的发展方向，而 CommonJS 模块作为一种特殊且老旧的方式，仅仅是提出 ES 模块标准之前的暂时性解决方案。ES 模块允许进行静态分析，从而有助于摇树(tree-shaking)和作用域提升(scope-hoisting)之类的优化工作。
中英文行数请保持一致

2020-07-04 02:51 UTC, lcxfs1991 commented on guide/zh/06-faqs.md
> +Tree-shaking，也被称为“live code inclusion”，是 Rollup 消除项目中并未实际使用到的代码的过程。它是一种[消除无效代码的方式](https://medium.com/@Rich_Harris/tree-shaking-versus-dead-code-elimination-d3765df85c80#.jnypozs9n)，但在优化输出内容大小方面可能比其他
中英文行数保持一致

2020-07-04 02:51 UTC, lcxfs1991 commented on guide/zh/06-faqs.md
> +Tree-shaking，也被称为“live code inclusion”，是 Rollup 消除项目中并未实际使用到的代码的过程。它是一种[消除无效代码的方式](https://medium.com/@Rich_Harris/tree-shaking-versus-dead-code-elimination-d3765df85c80#.jnypozs9n)，但在优化输出内容大小方面可能比其他
module graph 模块图

2020-07-04 02:51 UTC, lcxfs1991 commented on guide/zh/06-faqs.md
> +Rollup 致力于实现 ES 模块的规范，并不一定会考虑 Node.js，NPM，`require()`，和 CommonJS 的行为。所以，加载 CommonJS 模块的逻辑和使用 Node.js 的模块位置解析的逻辑都在插件中实现，Rollup 的核心代码并未默认提供这些功能。你只需要通过 `npm install` 安装 [commonjs](https://github.com/rol
都在可选的插件中实现

2020-07-04 02:51 UTC, lcxfs1991 commented on guide/zh/06-faqs.md
> +2. 从现实层面来讲，如果可以通过设计良好的 API 巧妙地分解这些问题，Rollup 的开发将变得更加轻松。Rollup 的核心代码非常庞大，所以一切阻止它变得臃肿的事情都是好事。与此同时，也能更容易地修复 bug 和加入新特性。Rollup 的代码库越精简，欠下的技术债务就越少。
行数对齐

2020-07-04 02:51 UTC, lcxfs1991 commented on guide/zh/06-faqs.md
>  #### Is Rollup meant for building libraries or applications?
翻译了就将英文标题删掉

2020-07-04 02:51 UTC, lcxfs1991 commented
每一段落请注意中英文行数保持一致哈

2020-07-04 08:31 UTC, parrotdance commented
> 每一段落请注意中英文行数保持一致哈

我觉得在一些情况下实在是难以取舍，中文相比于英文通常都更加简洁，强行保持行数一致会让译文变得臃肿，对阅读过程并没有帮助。
例如对第 7 行的翻译：

- ES modules are an official standard and the clear path forward for JavaScript code structure, whereas CommonJS modules are an idiosyncratic legacy format that served as a stopgap solution before ES modules had been proposed. ES modules allow static analysis that helps with optimizations like tree-shaking and scope-hoisting, and provide advanced features like circular references and live bindings.
- ES 模块是一个官方标准，也是 JavaScript 代码结构的明确的发展方向，而 CommonJS 模块是一种特殊且老旧的格式，仅仅在提出 ES 模块标准之前作为暂时性的解决方案。ES 模块允许进行静态分析，从而有助于摇树(tree-shaking)和作用域提升(scope-hoisting)之类的优化工作，同时提供了一些高级特性，例如循环引用和实时绑定。


我觉得已经很难再往里面塞别的文字了...能否举个例子？

2020-07-07 07:53 UTC, phobal commented
> > 每一段落请注意中英文行数保持一致哈
> 
> 我觉得在一些情况下实在是难以取舍，中文相比于英文通常都更加简洁，强行保持行数一致会让译文变得臃肿，对阅读过程并没有帮助。
> 例如对第 7 行的翻译：
> 
> * ES modules are an official standard and the clear path forward for JavaScript code structure, whereas CommonJS modules are an idiosyncratic legacy format that served as a stopgap solution before ES modules had been proposed. ES modules allow static analysis that helps with optimizations like tree-shaking and scope-hoisting, and provide advanced features like circular references and live bindings.
> * ES 模块是一个官方标准，也是 JavaScript 代码结构的明确的发展方向，而 CommonJS 模块是一种特殊且老旧的格式，仅仅在提出 ES 模块标准之前作为暂时性的解决方案。ES 模块允许进行静态分析，从而有助于摇树(tree-shaking)和作用域提升(scope-hoisting)之类的优化工作，同时提供了一些高级特性，例如循环引用和实时绑定。
> 
> 我觉得已经很难再往里面塞别的文字了...能否举个例子？

你可能误解了这里的中英文行数保持一致了，这里的 “中英文行数保持一致” 是指 中英文 **代码** 行数保持一致，而不是说中英文浏览器处理自动换行的行数要保持一致。
也就是说，只要译文的总代码行数要和原文保持一致，这样做最大的好处是方便 code review。

2020-07-09 12:22 UTC, parrotdance commented
哈，抱歉，确实是我误解了。
已根据修改意见更新了译文，还请抽空 review 一下。

2020-07-09 14:39 UTC, merged